In [4]:
from mxnet import nd
import numpy as np

In [9]:
img = nd.zeros(shape=(4, 4, 3))

In [10]:
img


[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
<NDArray 4x4x3 @cpu(0)>

In [13]:
rgb_mean = nd.array([1, 2, 3])
m = [4, 5, 6]

In [12]:
img + rgb_mean


[[[1. 2. 3.]
  [1. 2. 3.]
  [1. 2. 3.]
  [1. 2. 3.]]

 [[1. 2. 3.]
  [1. 2. 3.]
  [1. 2. 3.]
  [1. 2. 3.]]

 [[1. 2. 3.]
  [1. 2. 3.]
  [1. 2. 3.]
  [1. 2. 3.]]

 [[1. 2. 3.]
  [1. 2. 3.]
  [1. 2. 3.]
  [1. 2. 3.]]]
<NDArray 4x4x3 @cpu(0)>

In [15]:
img + nd.array(m)


[[[4. 5. 6.]
  [4. 5. 6.]
  [4. 5. 6.]
  [4. 5. 6.]]

 [[4. 5. 6.]
  [4. 5. 6.]
  [4. 5. 6.]
  [4. 5. 6.]]

 [[4. 5. 6.]
  [4. 5. 6.]
  [4. 5. 6.]
  [4. 5. 6.]]

 [[4. 5. 6.]
  [4. 5. 6.]
  [4. 5. 6.]
  [4. 5. 6.]]]
<NDArray 4x4x3 @cpu(0)>